//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalibrationNewGUI.Globalization {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalibrationNewGUI.Globalization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   자동저장 세팅과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AutoSave_Setting {
            get {
                return ResourceManager.GetString("AutoSave Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   자동 저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AutoSaveBox {
            get {
                return ResourceManager.GetString("AutoSaveBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   자동 저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AutoSaveMenu {
            get {
                return ResourceManager.GetString("AutoSaveMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   통신 속도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BaudRate {
            get {
                return ResourceManager.GetString("BaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CAL 옵션과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CAL_Option {
            get {
                return ResourceManager.GetString("CAL Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   캘리브레이션 세팅과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Calibration_Setting {
            get {
                return ResourceManager.GetString("Calibration Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CAL 세팅과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CalSettingMenu {
            get {
                return ResourceManager.GetString("CalSettingMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CAL 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CalStart {
            get {
                return ResourceManager.GetString("CalStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cal 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CalStartTip {
            get {
                return ResourceManager.GetString("CalStartTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cal 정지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CalStopTip {
            get {
                return ResourceManager.GetString("CalStopTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cal 타입과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CalType {
            get {
                return ResourceManager.GetString("CalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   채널과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   통신 세팅과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Comm_Setting {
            get {
                return ResourceManager.GetString("Comm Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   통신과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CommMenu {
            get {
                return ResourceManager.GetString("CommMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   접속과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   교정 션트 측정전류(mA)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CorrectionShuntCurr {
            get {
                return ResourceManager.GetString("CorrectionShuntCurr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   교정 션트 저항(uΩ)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CorrectionShuntReg {
            get {
                return ResourceManager.GetString("CorrectionShuntReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보정 전압 Meter(mV)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CorrectionVoltMeter {
            get {
                return ResourceManager.GetString("CorrectionVoltMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   포인트 생성과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CreatePoint {
            get {
                return ResourceManager.GetString("CreatePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   컨트롤러과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CtrlerBox {
            get {
                return ResourceManager.GetString("CtrlerBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Curr {
            get {
                return ResourceManager.GetString("Curr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전류 허용오차(±mA)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Curr_Allowable_Error {
            get {
                return ResourceManager.GetString("Curr Allowable Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전류 최소 간격({0})보다 낮은 값은 입력할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CurrIntervalErrMsg {
            get {
                return ResourceManager.GetString("CurrIntervalErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전류 입력 허용치를 벗어났습니다.
        ///최대값 : {0}
        ///최소값 : {1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CurrRangeOutErrMsg {
            get {
                return ResourceManager.GetString("CurrRangeOutErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 비트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DataBit {
            get {
                return ResourceManager.GetString("DataBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DataSaveTip {
            get {
                return ResourceManager.GetString("DataSaveTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   딜레이과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Delay {
            get {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   해제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DMM 접속 오류 : {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DmmConnErrMsg {
            get {
                return ResourceManager.GetString("DmmConnErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DMM 접속 해제 오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DmmDisconnErrMsg {
            get {
                return ResourceManager.GetString("DmmDisconnErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DMM 모델과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DmmModel {
            get {
                return ResourceManager.GetString("DmmModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DMM 세팅과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DmmSetting {
            get {
                return ResourceManager.GetString("DmmSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비어있는 셀이 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EmptyCellErrMsg {
            get {
                return ResourceManager.GetString("EmptyCellErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   테이블에 포인트가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EmptyTableErrMsg {
            get {
                return ResourceManager.GetString("EmptyTableErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   장비 연결이 끊겨있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EquiErrMsg {
            get {
                return ResourceManager.GetString("EquiErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   허용오차과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrRange {
            get {
                return ResourceManager.GetString("ErrRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   입력과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   간격과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Interval {
            get {
                return ResourceManager.GetString("Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어 적용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LangChangeCaption {
            get {
                return ResourceManager.GetString("LangChangeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경된 언어가 적용되려면 프로그램을 다시 시작해야합니다.
        ///적용하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LangChangeMsg {
            get {
                return ResourceManager.GetString("LangChangeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LogBox {
            get {
                return ResourceManager.GetString("LogBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그 표기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LogView {
            get {
                return ResourceManager.GetString("LogView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수동과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최대 전류 설정값 보다 큰 값은 입력할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MaximumCurrErrMsg {
            get {
                return ResourceManager.GetString("MaximumCurrErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   입력전류 상한(mV)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MaximumInputCurr {
            get {
                return ResourceManager.GetString("MaximumInputCurr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   입력전압 상한(mV)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MaximumInputVolt {
            get {
                return ResourceManager.GetString("MaximumInputVolt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최대 전압 설정값 보다 큰 값은 입력할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MaximumVoltErrMsg {
            get {
                return ResourceManager.GetString("MaximumVoltErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MCU 접속 오류 : {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string McuConnErrMsg {
            get {
                return ResourceManager.GetString("McuConnErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MCU 접속 해제 오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string McuDisconnErrMsg {
            get {
                return ResourceManager.GetString("McuDisconnErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MCU 세팅과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string McuSetting {
            get {
                return ResourceManager.GetString("McuSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실측 옵션과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MEA_Option {
            get {
                return ResourceManager.GetString("MEA Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   측정 지연시간(ms)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MeaDelay {
            get {
                return ResourceManager.GetString("MeaDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실측 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MeaStartTip {
            get {
                return ResourceManager.GetString("MeaStartTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실측 정지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MeaStopTip {
            get {
                return ResourceManager.GetString("MeaStopTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최소 전류 설정값 보다 작은 값은 입력할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MinimumCurrErrMsg {
            get {
                return ResourceManager.GetString("MinimumCurrErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   입력전류 하한(mV)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MinimumInputCurr {
            get {
                return ResourceManager.GetString("MinimumInputCurr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   입력전압 하한(mV)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MinimumInputVolt {
            get {
                return ResourceManager.GetString("MinimumInputVolt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최소 전압 설정값 보다 작은 값은 입력할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MinimumVoltErrMsg {
            get {
                return ResourceManager.GetString("MinimumVoltErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모델명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ModelName {
            get {
                return ResourceManager.GetString("ModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모니터링 제외과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MonitorExcept {
            get {
                return ResourceManager.GetString("MonitorExcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모니터링과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MonitoringBox {
            get {
                return ResourceManager.GetString("MonitoringBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   열기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기타 세팅과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Other_Setting {
            get {
                return ResourceManager.GetString("Other Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기타과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OtherMenu {
            get {
                return ResourceManager.GetString("OtherMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   출력 한계값과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OutputLimit {
            get {
                return ResourceManager.GetString("OutputLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   출력 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OutputStart {
            get {
                return ResourceManager.GetString("OutputStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   출력 중지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OutputStop {
            get {
                return ResourceManager.GetString("OutputStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최대값 보다 큰 값은 입력할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OverValueErrMsg {
            get {
                return ResourceManager.GetString("OverValueErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   패리티과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Parity {
            get {
                return ResourceManager.GetString("Parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   포인트 추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PointAddTip {
            get {
                return ResourceManager.GetString("PointAddTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   포인트 적용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PointApply {
            get {
                return ResourceManager.GetString("PointApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   포인트 삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PointDelTip {
            get {
                return ResourceManager.GetString("PointDelTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cal 포인트 다운로드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PointDownloadTip {
            get {
                return ResourceManager.GetString("PointDownloadTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   포인트 Down과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PointDownTip {
            get {
                return ResourceManager.GetString("PointDownTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   중복된 포인트는 허용하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PointOverlapErrMsg {
            get {
                return ResourceManager.GetString("PointOverlapErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cal 포인트 업로드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PointUploadTip {
            get {
                return ResourceManager.GetString("PointUploadTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   포인트 Up과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PointUpTip {
            get {
                return ResourceManager.GetString("PointUpTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   포트 번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PortName {
            get {
                return ResourceManager.GetString("PortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   결과데이터 자동저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResultData_AutoSave {
            get {
                return ResourceManager.GetString("ResultData AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   재측정 횟수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Retry_Count {
            get {
                return ResourceManager.GetString("Retry Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   세이브 파일 Prefix과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SaveFile_Prefix {
            get {
                return ResourceManager.GetString("SaveFile Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장 완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SaveOkMsg {
            get {
                return ResourceManager.GetString("SaveOkMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   채널 선택과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SelectCh {
            get {
                return ResourceManager.GetString("SelectCh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시리얼 번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SerialNum {
            get {
                return ResourceManager.GetString("SerialNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   션트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Shunt {
            get {
                return ResourceManager.GetString("Shunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   션트 세팅과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Shunt_Setting {
            get {
                return ResourceManager.GetString("Shunt Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   션트&amp;전압과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShuntMenu {
            get {
                return ResourceManager.GetString("ShuntMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   표준 션트 측정전류(mA)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StandardShuntCurr {
            get {
                return ResourceManager.GetString("StandardShuntCurr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   표준 션트 저항(nΩ)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StandardShuntReg {
            get {
                return ResourceManager.GetString("StandardShuntReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   표준 전압 Meter(mV)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StandartVoltMeter {
            get {
                return ResourceManager.GetString("StandartVoltMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스캔 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StartScan {
            get {
                return ResourceManager.GetString("StartScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정지 비트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StopBit {
            get {
                return ResourceManager.GetString("StopBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최소값 보다 작은 값은 입력할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UnderValueErrMsg {
            get {
                return ResourceManager.GetString("UnderValueErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정수만 입력 가능합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ValueErrMsg {
            get {
                return ResourceManager.GetString("ValueErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전압과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Volt {
            get {
                return ResourceManager.GetString("Volt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전압 허용오차(±mV)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Volt_Allowable_Error {
            get {
                return ResourceManager.GetString("Volt Allowable Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전압 미터과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Volt_Meter {
            get {
                return ResourceManager.GetString("Volt Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전압 최소 간격({0})보다 낮은 값은 입력할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VoltIntervalErrMsg {
            get {
                return ResourceManager.GetString("VoltIntervalErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전압 입력 허용치를 벗어났습니다.
        ///최대값 : {0}
        ///최소값 : {1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VoltRangeOutErrMsg {
            get {
                return ResourceManager.GetString("VoltRangeOutErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   잘못된 데이터가 포함되어 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WrongDataErrMsg {
            get {
                return ResourceManager.GetString("WrongDataErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zero 오프셋과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Zero_Offset {
            get {
                return ResourceManager.GetString("Zero Offset", resourceCulture);
            }
        }
    }
}
